name: build

on:
  schedule:
    - cron: "0 2 * * 3"
  workflow_dispatch: {}

jobs:
  data:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Remove software from the runner image
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          python --version
          sudo apt-get install -y -qq libicu-dev wget
          pip install pyicu awscli
          pip install -r requirements.txt
      - name: Fetch and parse the data
        run: |
          make data/fragments.json
          rm data/statements.latest.jsonl.gz
      - name: Aggregate fragmented entities
        run: |
          mkdir -p data/export
          sort -o data/sorted.json data/fragments.json
          rm data/fragments.json
          ftm sorted-aggregate -i data/sorted.json -o data/export/openownership.json
      - name: Publish data to data.opensanctions.org
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --no-progress --cache-control "public, max-age=64600" --metadata-directive REPLACE --acl public-read data/export s3://data.opensanctions.org/contrib/openownership
